import { useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(0);

  return (
    <>
      <Head>
        <title>Вифания Анапа</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <CssBaseline />
          <Container fixed>
            <Box sx={{ bgcolor: "#cfe8fc", height: "100vh" }}>
              <img src="/picture.png" alt="Photo" />
              <h1 style={{color: "red", backgroundColor: "yellow"}}> Olga </h1>
              <p>Hello word</p>
              <a href="https://propokot.ru/" rel="noreferrer" target="_blank" class="btn btn-primary">
              <button style={{color: "yellow", backgroundColor: "grey"}}>like</button>
              </a>
            </Box>
          </Container>
        </div>
      </main>
    </>
  );
}
