import {useState} from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";
import ButtonGroup from "@mui/material/ButtonGroup";
import Checkboxes from "src/components/checkboxes";


import Tooltip from '@mui/material/Tooltip';
import Fade from '@mui/material/Fade';
import Zoom from '@mui/material/Zoom';


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [count, setCount] = useState(0);

  return (
    <>
      <Head>
        <title>Вифания Анапа</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       
          <Button variant="contained" disableElevation>
            Главная
          </Button>

          <ButtonGroup
            variant="contained"
            aria-label="outlined primary button group"
          >
            <Button onClick={() => { setCount(count + 1); }}>Plus</Button>
            <Button onClick={() => { setCount(count - 1); }}>Minus</Button>
            <Button>Three</Button>
          </ButtonGroup>
          <Checkboxes/>
          {count}

         
        <div>
      <Tooltip title="Add">
        <Button>Главная</Button>
      </Tooltip>
      <Tooltip
        TransitionComponent={Fade}
        TransitionProps={{ timeout: 600 }}
        title="Add"      >
        <Button>Вы гость?</Button>
      </Tooltip>
      <Tooltip TransitionComponent={Zoom} title="Add">
        <Button>Слово</Button>
      </Tooltip>
      <Tooltip TransitionComponent={Fade} title="Add">
        <Button>События</Button>
      </Tooltip>

    </div>
   

      </main>
    </>
  );
}
